### ISSUE TITLE
UNREGISTERED_PLATFORM"

### ISSUE THREAD

**Issue by Liziqiuqiu** [doldsimo/lti-1.3-canvas-lms#3]
I am not sure if there is something I haven't set up correctly. I ran the backend and configured the developer key in the Canvas test server, but I encountered the following error. The test server is an Instructure-hosted server that uses HTTPS connection, and I used ngrok to create an HTTPS localhost.
<img width="895" alt="developer key" src="https://github.com/doldsimo/lti-1.3-canvas-lms/assets/132622020/0b20b835-7d00-4dca-af2c-e6c8109754ad">

{"status":400,"error":"Bad Request","details":{"message":"UNREGISTERED_PLATFORM"}}

```

const path = require('path')
const routes = require('./src/routes')
const lti = require('ltijs').Provider

// Setup
lti.setup('Thsisnenkskejeekw',
  {
    url:'mongodb://localhost/ltidb?authSource=admin', // connection to mongodb
  }, {
  staticPath: path.join(__dirname, './public'), // Path to static files
  cookies: {
    secure: true, // Set secure to true if the testing platform is in a different domain and https is being used
    sameSite: 'None' // Set sameSite to 'None' if the testing platform is in a different domain and https is being used
  },
  devMode: false // Set DevMode to true if the testing platform is in a different domain and https is not being used
})

// When receiving successful LTI launch redirects to app
lti.onConnect(async (token, req, res) => {
  return res.sendFile(path.join(__dirname, './public/index.html'))
})

// When receiving deep linking request redirects to deep screen
lti.onDeepLinking(async (token, req, res) => {
  return lti.redirect(res, '/deeplink', { newResource: true })
})

// Setting up routes
lti.app.use(routes)

// Setup function
const setup = async () => {
  await lti.deploy({ port: 3000 })

  /**
   * Register platform
   */
  await lti.registerPlatform({
    url: 'https://ourinstitution.test.instructure.com', // or url : 'https://canvas.exampledomain.com' (depends on config form Canvas instance) if iss is changed in config/security.yml file! It must be the same as the iss
    name: 'Canvas',
    clientId: '93420000000000349',
    authenticationEndpoint: 'https://sso.test.canvaslms.com/api/lti/authorize_redirect',
    accesstokenEndpoint: 'https://sso.test.canvaslms.com/login/oauth2/token',
    authConfig: { method: 'JWK_SET', key: 'https://sso.test.canvaslms.com/api/lti/security/jwks' }
  })

}

setup()

```

**Comment by doldsimo** [comment]
Hi @Liziqiuqiu,

the error occurs when there is probably something wrong with your configuration.
Have you seen this [issue](https://github.com/doldsimo/lti-1.3-canvas-lms/issues/1)? 
If not, you can try the solutions I suggested in this issue.

Specifically, you could check whether the `url` parameters match. This should be the same as in the ISS value in the config/security.yml file, so it depends on the config form the Canvas Instance.

**Comment by Liziqiuqiu** [comment]
Hi Simon,
Thank you so much for the suggestion. I updated the URI to 'https://canvas.test.instructure.com/' (for a Instructure-hosted test server), and it works. Your assistance is greatly appreciated.

By the way, I have also encountered another issue. The '/grade' and '/members' endpoints do not work. The code remains the same as in your repo.

I chose the LTI 1.3 advantage services when I registered the developer key and then examined the idtoken.platformContext. I found that I have the necessary scope, 'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem'. However, the `const response = await lti.Grade.getLineItems(idtoken, { resourceLinkId: true })` and `const lineItem = await lti.Grade.createLineItem(idtoken, newLineItem)` calls failed.

Have you encountered similar situations before, or could you please provide some guidance for troubleshooting?

**error:** 
POST /grade                                  500 Internal Server Error
GET  /members                              500 Internal Server Error 

**the platformContext.endpoint info**
  endpoint: {
    scope: [
      'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem',
      'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly',
      'https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly',
      'https://purl.imsglobal.org/spec/lti-ags/scope/score',
      'https://canvas.instructure.com/lti-ags/progress/scope/show'
    ],

**Code of the routes.js**
```
const router = require('express').Router()
const path = require('path')

// Requiring Ltijs
const lti = require('ltijs').Provider

// Grading route
router.post('/grade', async (req, res) => {
  try {
    const idtoken = res.locals.token // IdToken
    const score = req.body.grade // User numeric score sent in the body
    console.log(idtoken.platformContext)
    // Creating Grade object
    const gradeObj = {
      userId: idtoken.user,
      scoreGiven: score,
      scoreMaximum: 100,
      activityProgress: 'Completed',
      gradingProgress: 'FullyGraded'
    }

    // Selecting linetItem ID
    let lineItemId = idtoken.platformContext.endpoint.lineitem // Attempting to retrieve it from idtoken
    if (!lineItemId) {
      console.log("inside if");
      const response = await lti.Grade.getLineItems(idtoken, { resourceLinkId: true })
      // console.log(response);
      const lineItems = response.lineItems
      if (lineItems.length === 0) {
        // Creating line item if there is none
        console.log('Creating new line item')
        const newLineItem = {
          scoreMaximum: 100,
          label: 'Grade',
          tag: 'grade',
          resourceLinkId: idtoken.platformContext.resource.id,
        }
        console.log("lineItem");
        const lineItem = await lti.Grade.createLineItem(idtoken, newLineItem)
        console.log(lineItem);
        // const lineItem = await lti.Grade.createLineItem(idtoken, newLineItem)
        console.log("after creting lineItem");
        lineItemId = lineItem.id
      } else lineItemId = lineItems[0].id
    }
    console.log("before sending grade");

    // Sending Grade
    const responseGrade = await lti.Grade.submitScore(idtoken, lineItemId, gradeObj)
    return res.send(responseGrade)
  } catch (err) {
    console.log(err.message)
    return res.status(500).send({ err: err.message })
  }
})

// Names and Roles route
router.get('/members', async (req, res) => {
  try {
    const result = await lti.NamesAndRoles.getMembers(res.locals.token)
    if (result) return res.send(result.members)
    return res.sendStatus(500)
  } catch (err) {
    console.log(err.message)
    return res.status(500).send(err.message)
  }
})

// Deep linking route
router.post('/deeplink', async (req, res) => {
  try {
    const resource = req.body

    const items = {
      type: 'ltiResourceLink',
      title: 'Ltijs Demo',
      custom: {
        name: resource.name,
        value: resource.value
      }
    }

    const form = await lti.DeepLinking.createDeepLinkingForm(res.locals.token, items, { message: 'Successfully Registered' })
    if (form) return res.send(form)
    return res.sendStatus(500)
  } catch (err) {
    console.log(err.message)
    return res.status(500).send(err.message)
  }
})

// Return available deep linking resources
router.get('/resources', async (req, res) => {
  const resources = [
    {
      name: 'Resource1',
      value: 'value1'
    },
    {
      name: 'Resource2',
      value: 'value2'
    },
    {
      name: 'Resource3',
      value: 'value3'
    }
  ]
  return res.send(resources)
})

// Get user and context information
router.get('/info', async (req, res) => {
  const token = res.locals.token

  const context = res.locals.context

  const info = {}
  if (token.userInfo) {
    if (token.userInfo.name) info.name = token.userInfo.name
    if (token.userInfo.email) info.email = token.userInfo.email
  }

  if (context.roles) info.roles = context.roles
  if (context.context) info.context = context.context

  return res.send(info)
})

// Wildcard route to deal with redirecting to React routes
router.get('*', (req, res) => res.sendFile(path.join(__dirname, '../public/index.html')))

module.exports = router
```

**Comment by Liziqiuqiu** [comment]
The HTTP 500 server error was an issue of the ltijs library:
https://github.com/Cvmcosta/ltijs/issues/193

**Comment by doldsimo** [comment]
@Liziqiuqiu thanks for the hint,
Yes, since this example application is based on ltijs you would have to follow the issue you linked.

I will close the issue.

If you have any other questions, you can create a new issue.

**Comment by Liziqiuqiu** [comment]
Hi Simon,
This is not an issue, but rather a question I've come across. However, I'm unsure where to seek help. I will remove this if it's not the appropriate place to post this question.

In the readme document, the second step is to set up a Canvas instance. I've followed the [Production Start](https://github.com/instructure/canvas-lms/wiki/Production-Start) tutorial and can access the instance. However, I'm unable to locate the login page; I don't know how to login into the system; all I can find is the public directory shown below. Could you please provide some guidance?
![image](https://github.com/doldsimo/lti-1.3-canvas-lms/assets/132622020/55256f13-53ca-4bd0-a915-e3fc6d901882)


Thank you so much!!!

Have a wonderful Christmas season ahead!

**Comment by doldsimo** [comment]
Hi @Liziqiuqiu,

Based on your question, I have created a new issue for a better overview.
We can discuss your question further [there](https://github.com/doldsimo/lti-1.3-canvas-lms/issues/4).
